version: '3'

services:
  nginx:
    #image: nginx
    build: ./docker_nginx

    # Hostname
    hostname: nginx_host

    # コンテナ名
    container_name: 'nginx_con01'
    
    volumes:
      - ./projects_srv/deposit_srv/static:/static
      #- ./nginx_srv/conf:/etc/nginx/conf.d
    ports:
     - "8082:80"
    depends_on:
     - wsl_deposit_srv_service_01

  wsl_deposit_srv_service_01:
    # os起動時(Docker起動時)にコンテナを再起動さる場合
    # restart: always
    
    # ComposeFileを実行しビルドされるときのルートパス
    # このフォルダにDockerファイルを置く
    build: ./docker_srv
    
    
    # DEV UWSGI起動
    # command: uwsgi --socket :8001 --chdir /workspace/deposit_srv --wsgi-file deposit_srv/wsgi.py
    # PROD UWSGI起動
    command: uwsgi --socket :8001 --chdir /workspace/deposit_srv --wsgi-file env/wsgi.py --master --processes 4 --threads 2
    # Django 単独起動
    #command: python manage.py runserver 0.0.0.0:8000 --settings env.settings_master
    #command: python manage.py runserver --settings env.settings_master

    # Hostname
    hostname: wslDepositSrvHost01

    # コンテナ名
    container_name: 'wslDepositSrvCon01'
    
    # コンテナ内のワーキングディレクトリ
    working_dir: '/workspace/deposit_srv'
    
    # コンテナを終了させたくない場合に設定
    tty: true
    #ports:
    #  - 8082:8001
    
    # ローカルフォルダとコンテナ内のマウントディレクトリの関連づけ
    volumes:
      - ./projects_srv:/workspace
    # PORT開放
    expose:
      - "8001"

  #######################################################
  # クライアント コンテナ
  #######################################################
  wsl_deposit_srv_client_01:
    build: ./docker
    # コンテナを終了させたくない場合に設定
    tty: true
    # コンテナ内のワーキングディレクトリ
    working_dir: '/projects/deposit'
    #起動
    command: npm start
    # コンテナ名
    container_name: 'wsl_deposit_cli_con_01'
    # Hostname
    hostname: wsl_deposit_cli_host_01
    ports:
      - "3000:3000"
    volumes:
      - "./projects:/projects"

